name: Test
on: push

jobs:
  test:
    runs-on: windows-latest
    env:
      PNPM_BIN: ${{ steps.pnpm_bin.outputs.pnpm-bin }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Get pnpm bin directory
        id: pnpm_bin
        run: echo "::set-output name=pnpm-bin::$(pnpm bin)"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run depcheck
        run: ${{ env.PNPM_BIN }}/depcheck
