name: Test
on:
  push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Get pnpm bin path
        id: pnpm_bin
        run: echo "::set-output name=pnpm-bin::$(pnpm bin)"

      - name: Run depcheck with path bash
        shell: bash
        run: ${{ steps.pnpm_bin.outputs.pnpm-bin }}/depcheck --ignores="depcheck,@graphql-codegen/cli,@testing-library/user-event,@tailwindcss/jit,autoprefixer,postcss,tailwindcss,sass,babel-eslint,eslint-config-next,stylelint,stylelint-config-upleveled,babel-jest,cypress,jest,jest-environment-jsdom,jest-puppeteer,playwright,puppeteer,expect,typescript,@types/*,sharp,@next/eslint-plugin-next,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint-plugin-upleveled,eslint-config-react-app,eslint-import-resolver-typescript,eslint-plugin-import,eslint-plugin-jsx-a11y,eslint-plugin-jsx-expressions,eslint-plugin-react-hooks,eslint-plugin-react,eslint-plugin-security,eslint-plugin-sonarjs,eslint-plugin-unicorn"

      - name: Run depcheck with path cmd
        shell: cmd
        run: ${{ steps.pnpm_bin.outputs.pnpm-bin }}/depcheck --ignores="depcheck,@graphql-codegen/cli,@testing-library/user-event,@tailwindcss/jit,autoprefixer,postcss,tailwindcss,sass,babel-eslint,eslint-config-next,stylelint,stylelint-config-upleveled,babel-jest,cypress,jest,jest-environment-jsdom,jest-puppeteer,playwright,puppeteer,expect,typescript,@types/*,sharp,@next/eslint-plugin-next,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint-plugin-upleveled,eslint-config-react-app,eslint-import-resolver-typescript,eslint-plugin-import,eslint-plugin-jsx-a11y,eslint-plugin-jsx-expressions,eslint-plugin-react-hooks,eslint-plugin-react,eslint-plugin-security,eslint-plugin-sonarjs,eslint-plugin-unicorn"

      - name: Run depcheck with path powershell
        shell: powershell
        run: ${{ steps.pnpm_bin.outputs.pnpm-bin }}/depcheck --ignores="depcheck,@graphql-codegen/cli,@testing-library/user-event,@tailwindcss/jit,autoprefixer,postcss,tailwindcss,sass,babel-eslint,eslint-config-next,stylelint,stylelint-config-upleveled,babel-jest,cypress,jest,jest-environment-jsdom,jest-puppeteer,playwright,puppeteer,expect,typescript,@types/*,sharp,@next/eslint-plugin-next,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint-plugin-upleveled,eslint-config-react-app,eslint-import-resolver-typescript,eslint-plugin-import,eslint-plugin-jsx-a11y,eslint-plugin-jsx-expressions,eslint-plugin-react-hooks,eslint-plugin-react,eslint-plugin-security,eslint-plugin-sonarjs,eslint-plugin-unicorn"
