name: Test
on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run Depcheck
        run: pnpm depcheck --ignores="depcheck,@graphql-codegen/cli,@testing-library/user-event,@tailwindcss/jit,autoprefixer,postcss,tailwindcss,sass,babel-eslint,eslint-config-next,stylelint,stylelint-config-upleveled,babel-jest,cypress,jest,jest-environment-jsdom,jest-puppeteer,playwright,puppeteer,expect,typescript,@types/*,sharp,@next/eslint-plugin-next,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint-plugin-upleveled,eslint-config-react-app,eslint-import-resolver-typescript,eslint-plugin-import,eslint-plugin-jsx-a11y,eslint-plugin-jsx-expressions,eslint-plugin-react-hooks,eslint-plugin-react,eslint-plugin-security,eslint-plugin-sonarjs,eslint-plugin-unicorn"
